### ISSUE TITLE
On IE8, the canvas doesn't move along with the map.

### ISSUE THREAD

**Issue by jdduarte** [brendankenny/CanvasLayer#2]
This is because moving the canvas is being done with the `transform` CSS property which IE8 doesn't support.

I have a simple PR which uses `margin-left` and `margin-top` instead, when the browser doesn't support `transform`.

I know IE8 is legacy but I had to do that change for my application. If you think it's useful to have it merged I can submit it. If not, I completely understand why and just feel free to close this issue.

**Comment by brendankenny** [comment]
Hmm, what do you do for canvas support? I didn't include a fallback for `transform` because the set of browsers that support `transform` (with and without prefixes) is essentially the same as browsers that support canvas. Not sure what e.g. [ExplorerCanvas](https://github.com/arv/ExplorerCanvas) performance is actually going to look like while panning the map.

**Comment by jdduarte** [comment]
Sorry, forgot to mention that.

Yes, used ExplorerCanvas for canvas support. It performs OK but of course not as good as any modern browser.

I was unsure to submit the PR exactly because it's a feature that needs another library (ExplorerCanvas) to be seen and targets a browser which shouldn't be targeted any longer. Well the more I think about it the less it makes sense to have it merged. Happy to close this one really...

**Comment by quantuminformation** [comment]
I don't think its wise to include ExplorerCanvas in this.

**Comment by jdduarte** [comment]
@QuantumInformation The objective is not to include ExplorerCanvas. The main goal was to include a small change in CanvasLayer that would make it work when someone would use it, on their own, in conjunction with ExplorerCanvas.

Will close this one.

**Comment by quantuminformation** [comment]
Ah, ok makes sense)
