### ISSUE TITLE
Vertical resize 

### ISSUE THREAD

**Issue by NeuralSpaz** [brendankenny/CanvasLayer#4]
hello_webgl canvas translates independent from map on a vertical window resize, 
 as canvasLayerOptions: resizeHandler does not seem to getting called on a window resize event.

workaround:  https://github.com/NeuralSpaz/CanvasLayer/commit/213045e7958077f80c92cecbc88b529db0adee25 for hello_webgl

**Comment by caioiglesias** [comment]
The resize event must be triggered:

window.addEventListener("resize", function(){google.maps.event.trigger(map, 'resize')});
